BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Usuarios] DROP CONSTRAINT [DF_Usuarios_Tipo];
ALTER TABLE [dbo].[Usuarios] ALTER COLUMN [Tipo] NVARCHAR(1000) NOT NULL;
ALTER TABLE [dbo].[Usuarios] ADD CONSTRAINT [Usuarios_Tipo_df] DEFAULT 'CLIENTE' FOR [Tipo];

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
