import { useCallback, useEffect, useMemo, useState } from "react";
import { FaExclamationTriangle, FaHistory } from "react-icons/fa";
import { aprovarOrcamento, excluirCategoriaOrcamento, excluirCustoProjeto, getOrcamento, getOrcamentoProjetos, reabrirOrcamento, salvarCategoriaOrcamento, salvarCustoProjeto, salvarOrcamento } from "../../services/Projetos/OrcamentoService";
import { CrudModal } from "./CrudModal";
import { AccessState, EmptyState, FeedbackMessage, LoadingState } from "./CrudFeedback";
import CrudGrid from "./CrudGrid";
import { useCrudSelection } from "../hooks/useCrudSelection";
import "../styles/crudGrid.css";
import "../styles/projectBudget.css";

const emptyPanel = { recursos: [], tarefas: [], financeiro: null, permissoes: {} };
const emptyCategory = { nome: "", valorPlanejado: "0", valorComprometido: "0", valorRealizado: "0" };
const emptyCost = { tipo: "FIXO", descricao: "", categoriaId: "", recursoId: "", tarefaId: "", horas: "", taxaHora: "", valorPlanejado: "0", valorComprometido: "0", valorRealizado: "0" };
const userLabel = (user) => user?.nome || user?.login || user?.email || "Não atribuído";
const resourceLabel = (resource) => userLabel(resource?.usuario);
const money = (value, currency = "BRL") => new Intl.NumberFormat("pt-BR", { style: "currency", currency }).format(Number(value || 0));
const hours = (minutes) => `${(Number(minutes || 0) / 60).toLocaleString("pt-BR", { maximumFractionDigits: 2 })} h`;

function MoneyFields({ value, setValue, hidePlanned = false }) {
  return <>{!hidePlanned && <label>Planejado<input required min="0" step="0.01" type="number" value={value.valorPlanejado} onChange={(event) => setValue({ ...value, valorPlanejado: event.target.value })} /></label>}<label>Comprometido<input required min="0" step="0.01" type="number" value={value.valorComprometido} onChange={(event) => setValue({ ...value, valorComprometido: event.target.value })} /></label><label>Realizado<input required min="0" step="0.01" type="number" value={value.valorRealizado} onChange={(event) => setValue({ ...value, valorRealizado: event.target.value })} /></label></>;
}

function CostFields({ value, setValue, categories, resources, tasks, currency }) {
  const selectedResource = resources.find((item) => item.id === value.recursoId);
  const availableTasks = tasks.filter((item) => item.recursoIds.includes(selectedResource?.cadastroRecursoId) && item.moeda === currency);
  return <><label>Tipo<select value={value.tipo} onChange={(event) => setValue({ ...value, tipo: event.target.value, ...(event.target.value === "FIXO" ? { recursoId: "", tarefaId: "", horas: "", taxaHora: "" } : {}) })}><option value="FIXO">Fixo</option><option value="RECURSO">Recurso</option></select></label><label>Descrição<input required value={value.descricao} onChange={(event) => setValue({ ...value, descricao: event.target.value })} /></label><label>Categoria<select value={value.categoriaId} onChange={(event) => setValue({ ...value, categoriaId: event.target.value })}><option value="">Sem categoria</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.nome}</option>)}</select></label>{value.tipo === "RECURSO" && <><label>Recurso cadastrado<select required value={value.recursoId} onChange={(event) => setValue({ ...value, recursoId: event.target.value, tarefaId: "" })}><option value="">Selecione</option>{resources.map((item) => <option key={item.id} value={item.id} disabled={!item.ativo && item.id !== value.recursoId}>{resourceLabel(item)}{item.ativo ? "" : " (inativo)"}</option>)}</select></label><label>Tarefa (opcional)<select value={value.tarefaId} disabled={!value.recursoId} onChange={(event) => setValue({ ...value, tarefaId: event.target.value })}><option value="">Sem tarefa específica</option>{availableTasks.map((item) => <option key={item.id} value={item.id} disabled={!item.ativo && item.id !== value.tarefaId}>{item.funcionalidade}{item.ativo ? "" : " (inativa)"}</option>)}</select><small>Somente tarefas do recurso na moeda {currency}.</small></label><label>Horas planejadas<input required min="0.01" step="0.01" type="number" value={value.horas} onChange={(event) => setValue({ ...value, horas: event.target.value })} /></label><label>Taxa/hora<input required min="0" step="0.0001" type="number" value={value.taxaHora} onChange={(event) => setValue({ ...value, taxaHora: event.target.value })} /></label></>}<MoneyFields value={value} setValue={setValue} hidePlanned={value.tipo === "RECURSO"} /></>;
}

export default function ProjectBudgetManagement() {
  const [projects, setProjects] = useState([]); const [projectId, setProjectId] = useState(""); const [panel, setPanel] = useState(emptyPanel);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const [category, setCategory] = useState(emptyCategory); const [cost, setCost] = useState(emptyCost); const [categoryEdit, setCategoryEdit] = useState(null); const [costEdit, setCostEdit] = useState(null);
  const [historyCost, setHistoryCost] = useState(null); const [categoriesToDelete, setCategoriesToDelete] = useState([]); const [costsToDelete, setCostsToDelete] = useState([]);
  const [budgetCurrency, setBudgetCurrency] = useState("BRL");
  const selectedProject = useMemo(() => projects.find((item) => item.id === projectId), [projectId, projects]);

  const load = useCallback(async (id = projectId) => { if (!id) { setPanel(emptyPanel); setLoading(false); return; } setLoading(true); setError(""); try { setPanel(await getOrcamento(id)); } catch (loadError) { setError(loadError.message); } finally { setLoading(false); } }, [projectId]);
  useEffect(() => { getOrcamentoProjetos().then((items) => { setProjects(items); setProjectId(items.find((item) => !item.arquivadoEm)?.id || items[0]?.id || ""); }).catch((loadError) => setError(loadError.message)).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (projectId) void load(projectId); }, [load, projectId]);

  const run = async (operation, message, reset) => { setSaving(true); setError(""); setSuccess(""); try { await operation(); reset?.(); setSuccess(message); await load(projectId); } catch (operationError) { setError(operationError.message); } finally { setSaving(false); } };
  const createBudget = () => run(() => salvarOrcamento({ projetoId: projectId, moeda: budgetCurrency }), "Orçamento-base criado.");
  const submitCategory = (event) => { event.preventDefault(); void run(() => salvarCategoriaOrcamento({ projetoId: projectId, ...category }), "Categoria adicionada.", () => setCategory(emptyCategory)); };
  const costPayload = (value) => ({ projetoId: projectId, ...(value.id ? { id: value.id, versao: value.versao } : {}), categoriaId: value.categoriaId || null, tipo: value.tipo, descricao: value.descricao, recursoId: value.tipo === "RECURSO" ? value.recursoId : null, tarefaId: value.tipo === "RECURSO" ? value.tarefaId || null : null, quantidadeMinutos: value.tipo === "RECURSO" ? Math.round(Number(value.horas) * 60) : null, taxaHora: value.tipo === "RECURSO" ? value.taxaHora : null, valorPlanejado: value.valorPlanejado, valorComprometido: value.valorComprometido, valorRealizado: value.valorRealizado });
  const submitCost = (event) => { event.preventDefault(); void run(() => salvarCustoProjeto(costPayload(cost)), "Custo registrado.", () => setCost(emptyCost)); };
  const submitCategoryEdit = (event) => { event.preventDefault(); void run(() => salvarCategoriaOrcamento({ projetoId: projectId, ...categoryEdit }), "Categoria alterada.", () => setCategoryEdit(null)); };
  const submitCostEdit = (event) => { event.preventDefault(); void run(() => salvarCustoProjeto(costPayload(costEdit)), "Custo alterado.", () => setCostEdit(null)); };
  const confirmCategoryRemoval = (event) => { event.preventDefault(); void run(async () => { for (const item of categoriesToDelete) await excluirCategoriaOrcamento({ projetoId: projectId, id: item.id, versao: item.versao }); }, categoriesToDelete.length > 1 ? "Categorias excluídas." : "Categoria excluída.", () => setCategoriesToDelete([])); };
  const confirmCostRemoval = (event) => { event.preventDefault(); void run(async () => { for (const item of costsToDelete) await excluirCustoProjeto({ projetoId: projectId, id: item.id, versao: item.versao }); }, costsToDelete.length > 1 ? "Custos excluídos." : "Custo excluído.", () => setCostsToDelete([])); };

  const finance = panel.financeiro; const permissions = panel.permissoes || {};
  const categories = useMemo(() => finance?.categorias || [], [finance]);
  const costs = useMemo(() => finance?.custos || [], [finance]);
  const categorySelection = useCrudSelection(categories);
  const costSelection = useCrudSelection(costs);
  const canMaintain = finance?.status === "RASCUNHO" && permissions.podeGerenciarFinanceiro && !selectedProject?.arquivadoEm;
  const categoryName = (id) => finance?.categorias.find((item) => item.id === id)?.nome || "Sem categoria";
  const isOverBudget = (item) => Number(item.valorComprometido) > Number(item.valorPlanejado) || Number(item.valorRealizado) > Number(item.valorPlanejado);
  const editCost = (item) => setCostEdit({ id: item.id, versao: item.versao, tipo: item.tipo, descricao: item.descricao, categoriaId: item.categoriaId || "", recursoId: item.recursoId || "", tarefaId: item.tarefaId || "", horas: item.quantidadeMinutos ? String(Number(item.quantidadeMinutos) / 60) : "", taxaHora: item.taxaHora || "", valorPlanejado: item.valorPlanejado, valorComprometido: item.valorComprometido, valorRealizado: item.valorRealizado });

  return <section className="crud-grid project-budget">
    <header className="crud-grid-header budget-header"><div><span className="workspace-label">Gestão financeira</span><h2>Orçamento do projeto</h2><p>Gerencie exclusivamente orçamento, categorias, custos e aprovação financeira.</p></div><label><span>Projeto</span><select value={projectId} onChange={(event) => setProjectId(event.target.value)}><option value="">Selecione</option>{projects.map((item) => <option key={item.id} value={item.id}>{item.chave} — {item.nome}{item.arquivadoEm ? " (arquivado)" : ""}</option>)}</select></label></header>
    {error && <FeedbackMessage type="error" compact>{error}</FeedbackMessage>}{success && <FeedbackMessage type="success" compact>{success}</FeedbackMessage>}{selectedProject?.arquivadoEm && <AccessState type="readonly" compact>Projeto arquivado.</AccessState>}
    {loading ? <LoadingState message="Carregando orçamento..." /> : !permissions.podeVisualizarFinanceiro ? <AccessState>Você não possui acesso aos dados financeiros deste projeto.</AccessState> : !finance ? <EmptyState title="Nenhum orçamento-base cadastrado" action={permissions.podeGerenciarFinanceiro && !selectedProject?.arquivadoEm ? <div className="budget-create-controls"><label><span>Moeda do orçamento</span><input required aria-label="Moeda do orçamento" value={budgetCurrency} maxLength={3} pattern="[A-Z]{3}" list="budget-currencies" onChange={(event) => setBudgetCurrency(event.target.value.toUpperCase().replace(/[^A-Z]/g, "").slice(0, 3))} /></label><datalist id="budget-currencies"><option value="BRL" /><option value="USD" /><option value="EUR" /></datalist><button type="button" onClick={createBudget} disabled={saving || budgetCurrency.length !== 3}>Criar orçamento em {budgetCurrency || "..."}</button></div> : undefined} /> : <>
      <div className="budget-summary"><article><span>Planejado</span><strong>{money(finance.totalPlanejado, finance.moeda)}</strong></article><article><span>Comprometido</span><strong>{money(finance.totalComprometido, finance.moeda)}</strong></article><article><span>Realizado</span><strong>{money(finance.totalRealizado, finance.moeda)}</strong></article><article className={Number(finance.variacao) < 0 ? "risk" : ""}><span>Variação</span><strong>{money(finance.variacao, finance.moeda)}</strong></article></div>
      {(Number(finance.totalComprometido) > Number(finance.totalPlanejado) || Number(finance.totalRealizado) > Number(finance.totalPlanejado)) && <div className="budget-overrun"><FaExclamationTriangle /> O orçamento ultrapassou o valor planejado.</div>}
      <div className="budget-finance-heading"><h3>Orçamento {finance.moeda} · {finance.status === "APROVADO" ? "Aprovado" : "Rascunho"}</h3><div className="budget-finance-actions">{finance.status === "RASCUNHO" && permissions.podeAprovarOrcamento && <button type="button" onClick={() => run(() => aprovarOrcamento({ projetoId: projectId, id: finance.id, versao: finance.versao }), "Orçamento aprovado.")} disabled={saving}>Aprovar orçamento</button>}{finance.status === "APROVADO" && permissions.podeAprovarOrcamento && !selectedProject?.arquivadoEm && <button type="button" onClick={() => run(() => reabrirOrcamento({ projetoId: projectId, id: finance.id, versao: finance.versao }), "Orçamento reaberto.")} disabled={saving}>Reabrir para alteração</button>}</div></div>
      {canMaintain && <div className="budget-form-grid"><form onSubmit={submitCategory}><h3>Nova categoria</h3><label>Nome<input required value={category.nome} onChange={(event) => setCategory({ ...category, nome: event.target.value })} /></label><MoneyFields value={category} setValue={setCategory} /><div className="budget-form-actions"><button disabled={saving}>Adicionar categoria</button></div></form><form onSubmit={submitCost}><h3>Novo custo</h3><CostFields value={cost} setValue={setCost} categories={finance.categorias} resources={panel.recursos} tasks={panel.tarefas} currency={finance.moeda} /><div className="budget-form-actions"><button disabled={saving}>Adicionar custo</button></div>{cost.tipo === "RECURSO" && !panel.recursos.some((item) => item.ativo) && <small>Cadastre e ative o recurso na funcionalidade Recursos antes de criar o custo.</small>}</form></div>}
      <CrudGrid compact className="budget-section" kicker="Orçamento" title="Categorias" columns={[{ key: "nome", label: "Categoria" }, { key: "planejado", label: "Planejado", render: (item) => money(item.valorPlanejado, finance.moeda) }, { key: "comprometido", label: "Comprometido", render: (item) => money(item.valorComprometido, finance.moeda) }, { key: "realizado", label: "Realizado", render: (item) => money(item.valorRealizado, finance.moeda) }, { key: "variacao", label: "Variação", render: (item) => money(item.variacao, finance.moeda) }]} rows={categories} selectedId={categorySelection.selectedId} selectedIds={categorySelection.selectedIds} onSelect={categorySelection.selectRow} onToggleSelect={categorySelection.toggleSelected} onToggleSelectAll={categorySelection.toggleVisible} onEdit={(item) => setCategoryEdit({ ...item })} onDelete={(ids) => setCategoriesToDelete(categories.filter((item) => ids.includes(item.id)))} showCreate={false} showView={false} canEdit={canMaintain} canDelete={canMaintain} busy={saving} emptyMessage="Nenhuma categoria cadastrada." getRowClassName={(item) => isOverBudget(item) ? "budget-row-risk" : ""} getRowLabel={(item) => item.nome} />
      <CrudGrid compact className="budget-section" kicker="Orçamento" title="Custos" columns={[{ key: "descricao", label: "Descrição" }, { key: "categoria", label: "Categoria", render: (item) => categoryName(item.categoriaId) }, { key: "tipo", label: "Tipo", render: (item) => item.tipo === "RECURSO" ? "Recurso" : "Fixo" }, { key: "recurso", label: "Recurso", render: (item) => resourceLabel(item.recurso) }, { key: "tarefa", label: "Tarefa", render: (item) => item.tarefa?.funcionalidade || "—" }, { key: "horas", label: "Horas", render: (item) => item.quantidadeMinutos ? hours(item.quantidadeMinutos) : "—" }, { key: "taxa", label: "Taxa", render: (item) => item.taxaHora ? money(item.taxaHora, finance.moeda) : "—" }, { key: "planejado", label: "Planejado", render: (item) => money(item.valorPlanejado, finance.moeda) }, { key: "comprometido", label: "Comprometido", render: (item) => money(item.valorComprometido, finance.moeda) }, { key: "realizado", label: "Realizado", render: (item) => money(item.valorRealizado, finance.moeda) }, { key: "historico", label: "Histórico", render: (item) => item.taxas.length ? <button type="button" className="budget-history-button" onClick={(event) => { event.stopPropagation(); setHistoryCost(item); }}><FaHistory /> {item.taxas.length}</button> : "—" }]} rows={costs} selectedId={costSelection.selectedId} selectedIds={costSelection.selectedIds} onSelect={costSelection.selectRow} onToggleSelect={costSelection.toggleSelected} onToggleSelectAll={costSelection.toggleVisible} onEdit={editCost} onDelete={(ids) => setCostsToDelete(costs.filter((item) => ids.includes(item.id)))} showCreate={false} showView={false} canEdit={canMaintain} canDelete={canMaintain} busy={saving} emptyMessage="Nenhum custo cadastrado." getRowClassName={(item) => isOverBudget(item) ? "budget-row-risk" : ""} getRowLabel={(item) => item.descricao} />
    </>}
    {categoryEdit && <CrudModal mode="edit" title="Alterar categoria" onClose={() => setCategoryEdit(null)} onSubmit={submitCategoryEdit} formClassName="budget-edit-modal" actions={<><button type="button" className="secondary" onClick={() => setCategoryEdit(null)}>Cancelar</button><button type="submit" disabled={saving}>Salvar alterações</button></>}><div className="budget-edit-grid"><label>Nome<input required value={categoryEdit.nome} onChange={(event) => setCategoryEdit({ ...categoryEdit, nome: event.target.value })} /></label><MoneyFields value={categoryEdit} setValue={setCategoryEdit} /></div></CrudModal>}
    {costEdit && <CrudModal mode="edit" title="Alterar custo" onClose={() => setCostEdit(null)} onSubmit={submitCostEdit} formClassName="budget-edit-modal" actions={<><button type="button" className="secondary" onClick={() => setCostEdit(null)}>Cancelar</button><button type="submit" disabled={saving}>Salvar alterações</button></>}><div className="budget-edit-grid"><CostFields value={costEdit} setValue={setCostEdit} categories={finance?.categorias || []} resources={panel.recursos} tasks={panel.tarefas} currency={finance?.moeda} /></div></CrudModal>}
    {categoriesToDelete.length > 0 && <CrudModal mode="delete" title="Excluir categoria" onClose={() => setCategoriesToDelete([])} onSubmit={confirmCategoryRemoval} formClassName="budget-delete-modal" actions={<><button type="button" className="secondary" onClick={() => setCategoriesToDelete([])}>Cancelar</button><button type="submit" className="danger" disabled={saving}>Excluir</button></>}><p>Confirma a exclusão {categoriesToDelete.length > 1 ? `das ${categoriesToDelete.length} categorias selecionadas` : <>da categoria <strong>{categoriesToDelete[0].nome}</strong></>}?</p></CrudModal>}
    {costsToDelete.length > 0 && <CrudModal mode="delete" title="Excluir custo" onClose={() => setCostsToDelete([])} onSubmit={confirmCostRemoval} formClassName="budget-delete-modal" actions={<><button type="button" className="secondary" onClick={() => setCostsToDelete([])}>Cancelar</button><button type="submit" className="danger" disabled={saving}>Excluir</button></>}><p>Confirma a exclusão {costsToDelete.length > 1 ? `dos ${costsToDelete.length} custos selecionados` : <>do custo <strong>{costsToDelete[0].descricao}</strong></>}?</p></CrudModal>}
    {historyCost && <CrudModal mode="view" title={`Histórico de taxa · ${historyCost.descricao}`} onClose={() => setHistoryCost(null)} onSubmit={(event) => event.preventDefault()} formClassName="budget-history-modal" actions={<button type="button" onClick={() => setHistoryCost(null)}>Fechar</button>}><div className="budget-history-list">{historyCost.taxas.map((item) => <article key={item.id}><strong>{money(item.taxaHora, finance?.moeda)}</strong><span>{userLabel(item.criadoPor)}</span><small>{new Date(item.criadoEm).toLocaleString("pt-BR")}</small></article>)}</div></CrudModal>}
  </section>;
}
