import { useCallback, useEffect, useMemo, useState } from "react";
import { FaCoins, FaEdit, FaExclamationTriangle, FaHistory, FaTrash } from "react-icons/fa";
import { aprovarOrcamento, excluirCategoriaOrcamento, excluirCustoProjeto, getOrcamento, getOrcamentoProjetos, reabrirOrcamento, salvarCategoriaOrcamento, salvarCustoProjeto, salvarOrcamento } from "../../services/Projetos/OrcamentoService";
import { CrudModal } from "./CrudModal";
import "../styles/crudGrid.css";
import "../styles/projectBudget.css";

const emptyPanel = { recursos: [], tarefas: [], financeiro: null, permissoes: {} };
const emptyCategory = { nome: "", valorPlanejado: "0", valorComprometido: "0", valorRealizado: "0" };
const emptyCost = { tipo: "FIXO", descricao: "", categoriaId: "", recursoId: "", tarefaId: "", horas: "", taxaHora: "", valorPlanejado: "0", valorComprometido: "0", valorRealizado: "0" };
const userLabel = (user) => user?.nome || user?.login || user?.email || "Não atribuído";
const resourceLabel = (resource) => userLabel(resource?.usuario);
const money = (value, currency = "BRL") => new Intl.NumberFormat("pt-BR", { style: "currency", currency }).format(Number(value || 0));
const hours = (minutes) => `${(Number(minutes || 0) / 60).toLocaleString("pt-BR", { maximumFractionDigits: 2 })} h`;

function MoneyFields({ value, setValue, hidePlanned = false }) {
  return <>{!hidePlanned && <label>Planejado<input required min="0" step="0.01" type="number" value={value.valorPlanejado} onChange={(event) => setValue({ ...value, valorPlanejado: event.target.value })} /></label>}<label>Comprometido<input required min="0" step="0.01" type="number" value={value.valorComprometido} onChange={(event) => setValue({ ...value, valorComprometido: event.target.value })} /></label><label>Realizado<input required min="0" step="0.01" type="number" value={value.valorRealizado} onChange={(event) => setValue({ ...value, valorRealizado: event.target.value })} /></label></>;
}

function CostFields({ value, setValue, categories, resources, tasks, currency }) {
  const availableTasks = tasks.filter((item) => item.projetoRecursoId === value.recursoId && item.moeda === currency);
  return <><label>Tipo<select value={value.tipo} onChange={(event) => setValue({ ...value, tipo: event.target.value, ...(event.target.value === "FIXO" ? { recursoId: "", tarefaId: "", horas: "", taxaHora: "" } : {}) })}><option value="FIXO">Fixo</option><option value="RECURSO">Recurso</option></select></label><label>Descrição<input required value={value.descricao} onChange={(event) => setValue({ ...value, descricao: event.target.value })} /></label><label>Categoria<select value={value.categoriaId} onChange={(event) => setValue({ ...value, categoriaId: event.target.value })}><option value="">Sem categoria</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.nome}</option>)}</select></label>{value.tipo === "RECURSO" && <><label>Recurso cadastrado<select required value={value.recursoId} onChange={(event) => setValue({ ...value, recursoId: event.target.value, tarefaId: "" })}><option value="">Selecione</option>{resources.map((item) => <option key={item.id} value={item.id} disabled={!item.ativo && item.id !== value.recursoId}>{resourceLabel(item)}{item.ativo ? "" : " (inativo)"}</option>)}</select></label><label>Tarefa (opcional)<select value={value.tarefaId} disabled={!value.recursoId} onChange={(event) => setValue({ ...value, tarefaId: event.target.value })}><option value="">Sem tarefa específica</option>{availableTasks.map((item) => <option key={item.id} value={item.id} disabled={!item.ativo && item.id !== value.tarefaId}>{item.funcionalidade}{item.ativo ? "" : " (inativa)"}</option>)}</select><small>Somente tarefas do recurso na moeda {currency}.</small></label><label>Horas planejadas<input required min="0.01" step="0.01" type="number" value={value.horas} onChange={(event) => setValue({ ...value, horas: event.target.value })} /></label><label>Taxa/hora<input required min="0" step="0.0001" type="number" value={value.taxaHora} onChange={(event) => setValue({ ...value, taxaHora: event.target.value })} /></label></>}<MoneyFields value={value} setValue={setValue} hidePlanned={value.tipo === "RECURSO"} /></>;
}

export default function ProjectBudgetManagement() {
  const [projects, setProjects] = useState([]); const [projectId, setProjectId] = useState(""); const [panel, setPanel] = useState(emptyPanel);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const [category, setCategory] = useState(emptyCategory); const [cost, setCost] = useState(emptyCost); const [categoryEdit, setCategoryEdit] = useState(null); const [costEdit, setCostEdit] = useState(null);
  const [historyCost, setHistoryCost] = useState(null); const [categoryToDelete, setCategoryToDelete] = useState(null); const [costToDelete, setCostToDelete] = useState(null);
  const [budgetCurrency, setBudgetCurrency] = useState("BRL");
  const selectedProject = useMemo(() => projects.find((item) => item.id === projectId), [projectId, projects]);

  const load = useCallback(async (id = projectId) => { if (!id) { setPanel(emptyPanel); setLoading(false); return; } setLoading(true); setError(""); try { setPanel(await getOrcamento(id)); } catch (loadError) { setError(loadError.message); } finally { setLoading(false); } }, [projectId]);
  useEffect(() => { getOrcamentoProjetos().then((items) => { setProjects(items); setProjectId(items.find((item) => !item.arquivadoEm)?.id || items[0]?.id || ""); }).catch((loadError) => setError(loadError.message)).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (projectId) void load(projectId); }, [load, projectId]);

  const run = async (operation, message, reset) => { setSaving(true); setError(""); setSuccess(""); try { await operation(); reset?.(); setSuccess(message); await load(projectId); } catch (operationError) { setError(operationError.message); } finally { setSaving(false); } };
  const createBudget = () => run(() => salvarOrcamento({ projetoId: projectId, moeda: budgetCurrency }), "Orçamento-base criado.");
  const submitCategory = (event) => { event.preventDefault(); void run(() => salvarCategoriaOrcamento({ projetoId: projectId, ...category }), "Categoria adicionada.", () => setCategory(emptyCategory)); };
  const costPayload = (value) => ({ projetoId: projectId, ...(value.id ? { id: value.id, versao: value.versao } : {}), categoriaId: value.categoriaId || null, tipo: value.tipo, descricao: value.descricao, recursoId: value.tipo === "RECURSO" ? value.recursoId : null, tarefaId: value.tipo === "RECURSO" ? value.tarefaId || null : null, quantidadeMinutos: value.tipo === "RECURSO" ? Math.round(Number(value.horas) * 60) : null, taxaHora: value.tipo === "RECURSO" ? value.taxaHora : null, valorPlanejado: value.valorPlanejado, valorComprometido: value.valorComprometido, valorRealizado: value.valorRealizado });
  const submitCost = (event) => { event.preventDefault(); void run(() => salvarCustoProjeto(costPayload(cost)), "Custo registrado.", () => setCost(emptyCost)); };
  const submitCategoryEdit = (event) => { event.preventDefault(); void run(() => salvarCategoriaOrcamento({ projetoId: projectId, ...categoryEdit }), "Categoria alterada.", () => setCategoryEdit(null)); };
  const submitCostEdit = (event) => { event.preventDefault(); void run(() => salvarCustoProjeto(costPayload(costEdit)), "Custo alterado.", () => setCostEdit(null)); };
  const confirmCategoryRemoval = (event) => { event.preventDefault(); void run(() => excluirCategoriaOrcamento({ projetoId: projectId, id: categoryToDelete.id, versao: categoryToDelete.versao }), "Categoria excluída.", () => setCategoryToDelete(null)); };
  const confirmCostRemoval = (event) => { event.preventDefault(); void run(() => excluirCustoProjeto({ projetoId: projectId, id: costToDelete.id, versao: costToDelete.versao }), "Custo excluído.", () => setCostToDelete(null)); };

  const finance = panel.financeiro; const permissions = panel.permissoes || {};
  const canMaintain = finance?.status === "RASCUNHO" && permissions.podeGerenciarFinanceiro && !selectedProject?.arquivadoEm;
  const categoryName = (id) => finance?.categorias.find((item) => item.id === id)?.nome || "Sem categoria";
  const isOverBudget = (item) => Number(item.valorComprometido) > Number(item.valorPlanejado) || Number(item.valorRealizado) > Number(item.valorPlanejado);
  const editCost = (item) => setCostEdit({ id: item.id, versao: item.versao, tipo: item.tipo, descricao: item.descricao, categoriaId: item.categoriaId || "", recursoId: item.recursoId || "", tarefaId: item.tarefaId || "", horas: item.quantidadeMinutos ? String(Number(item.quantidadeMinutos) / 60) : "", taxaHora: item.taxaHora || "", valorPlanejado: item.valorPlanejado, valorComprometido: item.valorComprometido, valorRealizado: item.valorRealizado });

  return <section className="crud-grid project-budget">
    <header className="crud-grid-header budget-header"><div><span className="workspace-label">Gestão financeira</span><h2>Orçamento do projeto</h2><p>Gerencie exclusivamente orçamento, categorias, custos e aprovação financeira.</p></div><label><span>Projeto</span><select value={projectId} onChange={(event) => setProjectId(event.target.value)}><option value="">Selecione</option>{projects.map((item) => <option key={item.id} value={item.id}>{item.chave} — {item.nome}{item.arquivadoEm ? " (arquivado)" : ""}</option>)}</select></label></header>
    {error && <div className="budget-feedback error">{error}</div>}{success && <div className="budget-feedback success">{success}</div>}{selectedProject?.arquivadoEm && <div className="budget-readonly">Projeto arquivado: somente leitura.</div>}
    {loading ? <div className="budget-empty">Carregando orçamento...</div> : !permissions.podeVisualizarFinanceiro ? <div className="budget-empty">Você não possui acesso aos dados financeiros deste projeto.</div> : !finance ? <div className="budget-empty"><FaCoins /><p>Nenhum orçamento-base cadastrado.</p>{permissions.podeGerenciarFinanceiro && !selectedProject?.arquivadoEm && <div className="budget-create-controls"><label><span>Moeda do orçamento</span><input required aria-label="Moeda do orçamento" value={budgetCurrency} maxLength={3} pattern="[A-Z]{3}" list="budget-currencies" onChange={(event) => setBudgetCurrency(event.target.value.toUpperCase().replace(/[^A-Z]/g, "").slice(0, 3))} /></label><datalist id="budget-currencies"><option value="BRL" /><option value="USD" /><option value="EUR" /></datalist><button type="button" onClick={createBudget} disabled={saving || budgetCurrency.length !== 3}>Criar orçamento em {budgetCurrency || "..."}</button></div>}</div> : <>
      <div className="budget-summary"><article><span>Planejado</span><strong>{money(finance.totalPlanejado, finance.moeda)}</strong></article><article><span>Comprometido</span><strong>{money(finance.totalComprometido, finance.moeda)}</strong></article><article><span>Realizado</span><strong>{money(finance.totalRealizado, finance.moeda)}</strong></article><article className={Number(finance.variacao) < 0 ? "risk" : ""}><span>Variação</span><strong>{money(finance.variacao, finance.moeda)}</strong></article></div>
      {(Number(finance.totalComprometido) > Number(finance.totalPlanejado) || Number(finance.totalRealizado) > Number(finance.totalPlanejado)) && <div className="budget-overrun"><FaExclamationTriangle /> O orçamento ultrapassou o valor planejado.</div>}
      <div className="budget-finance-heading"><h3>Orçamento {finance.moeda} · {finance.status === "APROVADO" ? "Aprovado" : "Rascunho"}</h3><div className="budget-finance-actions">{finance.status === "RASCUNHO" && permissions.podeAprovarOrcamento && <button type="button" onClick={() => run(() => aprovarOrcamento({ projetoId: projectId, id: finance.id, versao: finance.versao }), "Orçamento aprovado.")} disabled={saving}>Aprovar orçamento</button>}{finance.status === "APROVADO" && permissions.podeAprovarOrcamento && !selectedProject?.arquivadoEm && <button type="button" onClick={() => run(() => reabrirOrcamento({ projetoId: projectId, id: finance.id, versao: finance.versao }), "Orçamento reaberto.")} disabled={saving}>Reabrir para alteração</button>}</div></div>
      {canMaintain && <div className="budget-form-grid"><form onSubmit={submitCategory}><h3>Nova categoria</h3><label>Nome<input required value={category.nome} onChange={(event) => setCategory({ ...category, nome: event.target.value })} /></label><MoneyFields value={category} setValue={setCategory} /><div className="budget-form-actions"><button disabled={saving}>Adicionar categoria</button></div></form><form onSubmit={submitCost}><h3>Novo custo</h3><CostFields value={cost} setValue={setCost} categories={finance.categorias} resources={panel.recursos} tasks={panel.tarefas} currency={finance.moeda} /><div className="budget-form-actions"><button disabled={saving}>Adicionar custo</button></div>{cost.tipo === "RECURSO" && !panel.recursos.some((item) => item.ativo) && <small>Cadastre e ative o recurso na funcionalidade Recursos antes de criar o custo.</small>}</form></div>}
      <div className="budget-section"><h3>Categorias</h3><div className="budget-table-wrap"><table><thead><tr><th>Categoria</th><th>Planejado</th><th>Comprometido</th><th>Realizado</th><th>Variação</th>{canMaintain && <th>Ações</th>}</tr></thead><tbody>{finance.categorias.map((item) => <tr key={item.id} className={isOverBudget(item) ? "budget-row-risk" : ""}><td>{item.nome}</td><td>{money(item.valorPlanejado, finance.moeda)}</td><td>{money(item.valorComprometido, finance.moeda)}</td><td>{money(item.valorRealizado, finance.moeda)}</td><td>{money(item.variacao, finance.moeda)}</td>{canMaintain && <td><div className="budget-row-actions"><button type="button" onClick={() => setCategoryEdit({ ...item })} aria-label={`Editar categoria ${item.nome}`}><FaEdit /></button><button type="button" className="danger" onClick={() => setCategoryToDelete(item)} aria-label={`Excluir categoria ${item.nome}`}><FaTrash /></button></div></td>}</tr>)}</tbody></table></div>{!finance.categorias.length && <div className="budget-empty compact">Nenhuma categoria cadastrada.</div>}</div>
      <div className="budget-section"><h3>Custos</h3><div className="budget-table-wrap"><table><thead><tr><th>Descrição</th><th>Categoria</th><th>Tipo</th><th>Recurso</th><th>Tarefa</th><th>Horas</th><th>Taxa</th><th>Planejado</th><th>Comprometido</th><th>Realizado</th><th>Histórico</th>{canMaintain && <th>Ações</th>}</tr></thead><tbody>{finance.custos.map((item) => <tr key={item.id} className={isOverBudget(item) ? "budget-row-risk" : ""}><td>{item.descricao}</td><td>{categoryName(item.categoriaId)}</td><td>{item.tipo === "RECURSO" ? "Recurso" : "Fixo"}</td><td>{resourceLabel(item.recurso)}</td><td>{item.tarefa?.funcionalidade || "—"}</td><td>{item.quantidadeMinutos ? hours(item.quantidadeMinutos) : "—"}</td><td>{item.taxaHora ? money(item.taxaHora, finance.moeda) : "—"}</td><td>{money(item.valorPlanejado, finance.moeda)}</td><td>{money(item.valorComprometido, finance.moeda)}</td><td>{money(item.valorRealizado, finance.moeda)}</td><td>{item.taxas.length ? <button type="button" className="budget-history-button" onClick={() => setHistoryCost(item)}><FaHistory /> {item.taxas.length}</button> : "—"}</td>{canMaintain && <td><div className="budget-row-actions"><button type="button" onClick={() => editCost(item)} aria-label={`Editar custo ${item.descricao}`}><FaEdit /></button><button type="button" className="danger" onClick={() => setCostToDelete(item)} aria-label={`Excluir custo ${item.descricao}`}><FaTrash /></button></div></td>}</tr>)}</tbody></table></div>{!finance.custos.length && <div className="budget-empty compact">Nenhum custo cadastrado.</div>}</div>
    </>}
    {categoryEdit && <CrudModal mode="edit" title="Alterar categoria" onClose={() => setCategoryEdit(null)} onSubmit={submitCategoryEdit} formClassName="budget-edit-modal" actions={<><button type="button" className="secondary" onClick={() => setCategoryEdit(null)}>Cancelar</button><button type="submit" disabled={saving}>Salvar alterações</button></>}><div className="budget-edit-grid"><label>Nome<input required value={categoryEdit.nome} onChange={(event) => setCategoryEdit({ ...categoryEdit, nome: event.target.value })} /></label><MoneyFields value={categoryEdit} setValue={setCategoryEdit} /></div></CrudModal>}
    {costEdit && <CrudModal mode="edit" title="Alterar custo" onClose={() => setCostEdit(null)} onSubmit={submitCostEdit} formClassName="budget-edit-modal" actions={<><button type="button" className="secondary" onClick={() => setCostEdit(null)}>Cancelar</button><button type="submit" disabled={saving}>Salvar alterações</button></>}><div className="budget-edit-grid"><CostFields value={costEdit} setValue={setCostEdit} categories={finance?.categorias || []} resources={panel.recursos} tasks={panel.tarefas} currency={finance?.moeda} /></div></CrudModal>}
    {categoryToDelete && <CrudModal mode="delete" title="Excluir categoria" onClose={() => setCategoryToDelete(null)} onSubmit={confirmCategoryRemoval} formClassName="budget-delete-modal" actions={<><button type="button" className="secondary" onClick={() => setCategoryToDelete(null)}>Cancelar</button><button type="submit" className="danger" disabled={saving}>Excluir</button></>}><p>Confirma a exclusão da categoria <strong>{categoryToDelete.nome}</strong>?</p></CrudModal>}
    {costToDelete && <CrudModal mode="delete" title="Excluir custo" onClose={() => setCostToDelete(null)} onSubmit={confirmCostRemoval} formClassName="budget-delete-modal" actions={<><button type="button" className="secondary" onClick={() => setCostToDelete(null)}>Cancelar</button><button type="submit" className="danger" disabled={saving}>Excluir</button></>}><p>Confirma a exclusão do custo <strong>{costToDelete.descricao}</strong>?</p></CrudModal>}
    {historyCost && <CrudModal mode="view" title={`Histórico de taxa · ${historyCost.descricao}`} onClose={() => setHistoryCost(null)} onSubmit={(event) => event.preventDefault()} formClassName="budget-history-modal" actions={<button type="button" onClick={() => setHistoryCost(null)}>Fechar</button>}><div className="budget-history-list">{historyCost.taxas.map((item) => <article key={item.id}><strong>{money(item.taxaHora, finance?.moeda)}</strong><span>{userLabel(item.criadoPor)}</span><small>{new Date(item.criadoEm).toLocaleString("pt-BR")}</small></article>)}</div></CrudModal>}
  </section>;
}
